# Generated by Django 3.0.5 on 2021-01-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Mobile', models.CharField(max_length=10, unique=True)),
                ('Address', models.TextField(max_length=100)),
                ('Password', models.CharField(max_length=12)),
                ('Status', models.BooleanField(default=False)),
                ('IsSeller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_author', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.User')),
            ],
        ),
    ]
