# Generated by Django 3.1.5 on 2021-01-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Status',
            new_name='IsActive',
        ),
    ]
