# Generated by Django 3.1.5 on 2021-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
