# Generated by Django 3.1.5 on 2021-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_auto_20210202_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
