# Generated by Django 3.1.5 on 2021-02-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
