# Generated by Django 3.1.5 on 2021-02-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0010_auto_20210204_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='placeholder.webp', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
